### ISSUE TITLE
could you share pre-built sqlite databases?

### ISSUE THREAD

**Issue by vesper8** [blakeb211/HoldemPokerTrainer#1]
I would like to use use the sqlite db and then use a Web client to do the rest

Is there any chance you could include a pre-built sqlite database?

Or is there a way to run this on OSX?

The pre-built sqlite db would be very helpful considering it takes hours to build. If you could provide different ones for 2,3,4,5,6...10 players that would be even better!

Many thanks for your work on this modern Holdem Trainer!

**Comment by blakeb211** [comment]
I will get working on this. As far as building on OSX, this targets .Net Core. You should be able to build on OSX with Visual Studio for Mac --> Clone --> Build. All the libraries I used were cross platform .net core afaik.

**Comment by blakeb211** [comment]
Almost done rewriting so that database is a) smaller and b) much faster to read from

**Comment by vesper8** [comment]
fantastic! are you then also planning on making pre-generated databases available for download?

**Comment by blakeb211** [comment]
Yes. I will upload them as compressed files. They will be around 600 megabytes each, but much smaller when compressed. It's also possible I'll remove the table indexes and provide code to generate them...That would make the database file for each player around 350 megabytes uncompressed or 70 mb compressed... Would love to know more about the front end you're thinking of doing.

**Comment by vesper8** [comment]
hey that's great about the compressed databases, and also great about you trying a different approach with Cactus Kev's idea

As for what I intended to do with it.. well.. not too much for a start.. I just wanted to make this more accessible and nothing beats the web for that. I was going to base it off of https://codepen.io/ivanandonov/pen/KWwZzv and rewrite that in Vue.js with probably a Laravel backend for the rest api. This is simply the stack I am most used to. From there I would serve the data to the front-end with the idea being a simple Texas Holdem decision trainer.. because after one too many bad calls or bad decisions overall.. it led me to your project and I figured the world could use a modern take on decision training

**Comment by blakeb211** [comment]
@vesper8  : . I uploaded a pre-built database for 4-players into a folder called Pre-Built Databases. It is split into 90MB pieces zipped up so you have to unzip it and add it to a Databases\ folder for the Poker Training Mode to work with it. Email me at Blake.eLink_AT_gmail_DOT_com and I'll give you my whatsapp if you need any assistance.  I will close this pull request once I've added the databases for the other player counts.
